<?php
include('include/inc_db.php');
include('control_login.php');
 /* to transform a string in a json strin */
header("Cache-Control: no-cache, must-revalidate" );
header("Pragma: no-cache" );
header("Content-type: text/x-json");

function str_json($string){
 $string = str_replace('\\','\\\\',$string);
 $string = str_replace('"','\"',$string);
 return utf8_encode($string);
}


//////////////////////////////////////////////////////////////
////////////////////    SET VARIABLES    ////////////////////
/////////////////////////////////////////////////////////////
$table = 'quizzes'; /* request of table where script reads data */
$counter = 0; /* start counter */
if(isset($_POST['rp'])){
  $counter = $_POST['rp']; /* request of item per page (it's generated by flexigred plugin */
}
/* with this var you can add other conditions in where clausole of advaced search in query */
$additional_where = ''; /////////// insert here others conditions e.g. --> "author = 'jhon doe' and ...."
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////
//////////////////// SEARCH VARIABLES   //////////////////////
/////////////////////////////////////////////////////////////
$sqlsearch = ''; /* it's important for advanced search */
$sqlsearch_or = ''; /* it contains condition with or clausole in query (in this case it's not important to set)*/

if (isset($_POST['name_r']) && $_POST['name_r']){
 $sqlsearch .= " name Like '%".$_POST['name_r']."%' and ";
}

if (isset($_POST['expired_r']) && $_POST['expired_r']){
 $sqlsearch_or .= " (end_date <> '0000-00-00 00:00:00' and end_date <= '".date("Y-m-d 00:00:00")."') or ";
}
if (isset($_POST['not_expired_r']) && $_POST['not_expired_r']){
 $sqlsearch_or .= " (end_date = '0000-00-00 00:00:00' or end_date >= '".date("Y-m-d 00:00:00")."') and ";
}

if (isset($_POST['active_r']) && $_POST['active_r']){
 $sqlsearch_or .= " status = 1 or ";
}
if (isset($_POST['not_active_r']) && $_POST['not_active_r']){
 $sqlsearch_or .= " status = 0 or ";
}



/////////////////////////////////////////////////////////////////////////////////////////////////////////////
/* with this var "$additional_where_nosearch" you can add other conditions in where clausole in query if $sqlsearch = "" (not change it) */
$additional_where_nosearch = '';
if ($additional_where != ''){ 
   $additional_where_nosearch = ' where '.$additional_where;
   $additional_where .= ' and '.$additional_where;
}

$order_record = 'id'; /* record to sort data (if it's not specified in js code) */
$order_verse = 'desc'; /* sort order (if it's not specified in js code) */

/* some conditions for pagination (non change them) */
if (isset($_POST['sortname']) && $_POST['sortname'] != 'undefined'){ 
 $order_record = $_POST['sortname'];
}
if (isset($_POST['sortorder']) && $_POST['sortorder'] != 'undefined'){ 
 $order_verse = $_POST['sortorder'];
}
$pag = 1;
if (isset($_POST['page'])){ 
 $pag = $_POST['page'];
}
if (is_numeric($pag) == 0 || $pag < '1'){ 
 $pag = 1;
}
$limit_end = $counter;
$limit_start = ($pag - 1) * $limit_end;

if ($sqlsearch_or != ''){
  $sqlsearch = $sqlsearch . '('.$sqlsearch_or; 
}

 if ($sqlsearch != ''){ 
   if ($sqlsearch_or != ''){
    $sqlsearch = ' Where ' . substr($sqlsearch, 0, strlen($sqlsearch) - 4).')'.$additional_where;
   }else{
    $sqlsearch = ' Where ' . substr($sqlsearch, 0, strlen($sqlsearch) - 5).$additional_where;
   }
     $quanti = countRec('id',$table,$sqlsearch);
 }else{     
     $quanti = countRec('id',$table,$additional_where_nosearch);
 }
if($sqlsearch != ''){                      
  $sql = ' select * from '.$table.' ' . $sqlsearch . ' order by '.$order_record.' '.$order_verse.'  LIMIT ' . $limit_start . ', ' . $limit_end;
}else{
  $sql = 'select * from '.$table.$additional_where_nosearch.' order by '.$order_record.' '.$order_verse.'  LIMIT ' . $limit_start . ', ' . $limit_end;
}
$rs_result = execute($sql);

$result  = "{";
$result .= "\"page\":$pag,";
$result .= "\"total\":$quanti";
if($quanti > 0){
$result .= ",\"rows\":[";
while ($rs = mysql_fetch_array($rs_result)) {
   $img_del = '<img id="'.$rs['id'].'" src="'.path_img .'/del.png" style="cursor:pointer;margin-right:5px" alt="" class="delete" title="Delete" />'; 
   $img_get_code = '<img id="'.$rs['id'].'" rel="'.path_stored_quizzes.'/'.$rs['id'].'/'.$rs['code'].'.php" src="'.path_img .'/code.png" style="cursor:pointer;margin-right:5px" alt="" class="getcode" title="Get ShortCode to include this quiz in your pages" />';   
   $img_edit = '<img id="'.$rs['id'].'" rel="'.$rs['name'].'" src="'.path_img .'/edit.png" style="cursor:pointer;margin-right:5px" alt="" class="edit" title="Edit" />';
   $img_preview = '<a href="'.path_abs_sfw.'/preview.php?code='.$rs['code'].'&id='.$rs['id'].'" target="_blank"><img src="'.path_img .'/preview.png" style="cursor:pointer;margin-right:5px" alt="" class="preview" title="Quiz Preview" /></a>';
   if(!$rs['status'])
    $img_status = '<img src="'.path_img .'/exipred.png" title="Inactive" alt="" />';
   else
    $img_status = '<img src="'.path_img .'/active.png" title="Active" alt="" />';

   $result .= '{';
   $result .= '"id":"'.$rs['id'].'",';
   $result .= '"cell":{';
   $result .= '"id":"'.$rs['id'].'",';
   $result .= '"check":"'.str_json('<input type="checkbox" id="'.$rs['id'].'" value="'.$rs['id'].'" name="box_elimina[]" class="check_selezione" align="absmiddle" />').'",';
   $result .= '"id":"'.str_json($rs['id']).'",';
   $result .= '"name":"'.str_json($rs['name']).'",';
   
   $result .= '"creation_date":"'.str_json(view_date($rs['creation_date'])).'",';

   
   $result .= '"status":"'.str_json($img_status).'",'; 
   $result .= '"actions":"'.str_json($img_edit.$img_preview.$img_get_code.$img_del).'"';
   $result .= '}},';   
 }
$result = substr($result,0,strlen($result)-1); 
$result .= "]"; 
}
$result .= "}"; 
echo $result;
?>